### ISSUE TITLE
Datalab API not supported

### ISSUE THREAD

**Issue by jerme42** [L3-N0X/obsidian-marker#2]
Very sorry if I am a dummy.  I really don't know what I am doing. I am trying to configure the endpoint in the settings. I'm using the data lab api but it doesn't connect. I checked that the service is working fine. How do I properly format the endpoint in the settings page on obsidian?

**Comment by jerme42** [comment]
nice! As soon as obsidian publishes the update I will give it a test.

**Comment by L3-N0X** [comment]
Thanks for testing! 1.2.0 is now published correctly, so you can try and see if it works

**Comment by jerme42** [comment]
No probs. And thanks for the plugin! 

I get an error when trying to convert. here is the console log (if its helpful):

Error during PDF conversion: Error: Request failed, status 400
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

**Comment by jerme42** [comment]
Error.
 
plugin:marker-api:309 Error during PDF conversion: Error: Request failed, status 422
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

**Comment by L3-N0X** [comment]
This was way more complicated than I thought, but I used the same approach now for the self hosted version, and there It works. So I'm very confident now that it will work also for the datalab endpoint. Please test again with version 1.2.2 if this finally fixes the issue.

**Comment by jerme42** [comment]
connection test works. error on conversion. Maybe I'm doing something wrong here.
Error during PDF conversion: Error: Request failed, status 422
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

**Comment by L3-N0X** [comment]
Now it should really work, version 1.2.3 and if not, I still added more debugging messages so we can find the problem. But I think I already found the problem, now no 422 error comes up anymore, the request is now formatted correctly.

**Comment by jerme42** [comment]
Good news: no connection error. Bad news: no markdown file. Here is the console log after trying a few different pdfs. I tried them manually with a crappy py script and they work with the api so it isn't on that end I think. 

plugin:marker-api:317 Error in convertWithDatalab: TypeError: data is not iterable
    at Marker.processConversionResult (plugin:marker-api:459:29)
    at eval (plugin:marker-api:299:28)
eval @ plugin:marker-api:317
plugin:marker-api:318 Uncaught (in promise) Error: Error in convertWithDatalab: TypeError: data is not iterable
    at eval (plugin:marker-api:318:21)
plugin:marker-api:317 Error in convertWithDatalab: TypeError: data is not iterable
    at Marker.processConversionResult (plugin:marker-api:459:29)
    at eval (plugin:marker-api:299:28)
eval @ plugin:marker-api:317
plugin:marker-api:318 Uncaught (in promise) Error: Error in convertWithDatalab: TypeError: data is not iterable
    at eval (plugin:marker-api:318:21)
plugin:marker-api:317 Error in convertWithDatalab: TypeError: data is not iterable
    at Marker.processConversionResult (plugin:marker-api:459:29)
    at eval (plugin:marker-api:299:28)
eval @ plugin:marker-api:317
plugin:marker-api:318 Uncaught (in promise) Error: Error in convertWithDatalab: TypeError: data is not iterable
    at eval (plugin:marker-api:318:21)

**Comment by L3-N0X** [comment]
Okay, the error should now be fixed in 1.2.4, datalab once again differs from marker-api and doesn't return data the same way.

**Comment by jerme42** [comment]
the md is created but empty. Thanks for working on this!

**Comment by L3-N0X** [comment]
Sorry, this update took a bit longer, but now I had the time to look into it once again. Can you please test it again? I also added more logging to the function getting the results after starting the request in case it still doesn't work

**Comment by jerme42** [comment]
solved. well done. chapeau.
