### ISSUE TITLE
Main.ts CreateMarkdownFile problem 

### ISSUE THREAD

**Issue by EugeneChan00** [L3-N0X/obsidian-marker#8]
Thanks for building this plugin, had been playing with it a bit on my Mac, but I am having issue in using this in obsidian, it will not create any markdown files after conversion takes place (I am hosting it locally - the process does get executed and I get a status 200 towards the end of it)

Getting this error here - it seems like there is a bit of an issue with the createMarkdownFile at main.ts

Error during PDF conversion: TypeError: Cannot read properties of undefined (reading 'replace')
    at Marker.createMarkdownFile (plugin:marker-api:522:27)
    at Marker.processConversionResult (plugin:marker-api:490:18)
    at eval (plugin:marker-api:153:22)
    at async Marker.convertPDFToMD (plugin:marker-api:126:5)
    at async eval (plugin:marker-api:86:17)
eval @ plugin:marker-api:160

Going to be doing some trouble shooting this weekend, see what I can get out of it.

**Comment by L3-N0X** [comment]
Fixed in V1.3.0!
When still having problems, use the newest version of the self-hosted api by upgrading to this container:
https://hub.docker.com/r/wirawan/marker-api
