### ISSUE TITLE
 127.0.0.1:60469 - "POST /convert HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by pblack476** [L3-N0X/obsidian-marker#9]
Hi!

I am getting this error when Testing the connection to the marker-api selfhosted server.

The server is up and running

![image](https://github.com/user-attachments/assets/0c909072-8cd8-486e-b365-18091e9ddef0)

But I cannot connect to it via localhost:8080

Working w/ Windows 11

**Comment by L3-N0X** [comment]
I'm sorry but the current version of the api container doesn't work with the plugin yet and I am not able to get it running on my machine to integrate the new version.

I am running https://hub.docker.com/r/savatar101/marker-api v0.3 myself and this version is still working fine for me.

I'll try to fix it as soon as possible!

**Comment by L3-N0X** [comment]
Fixed in V1.3.0!
When still having problems, use the newest version of the self-hosted api by upgrading to this container:
https://hub.docker.com/r/wirawan/marker-api
